#define BASE_PATH "/var/www/html/"
#define INTRANET_PATH "/var/www/html/intranet/*"
#define LIVE_PATH "/var/www/html/live/"
#define LIVE_BACKUP_PATH "/var/www/html/live/*"
#define BACKUP_PATH "/var/www/html/backup/"
#define LOG_PATH "/var/www/html/logs/"
#define QUEUE_NAME "/assignmentqueue"
#define MAX_BUFFER_LENGTH 1024
#define MAX_COMMAND_LENGTH 256